// This file is automatically generated by Firebase Studio.
// Do not edit manually.

// To change which Firebase project your app is connected to, edit the `.firebaserc` file with the
// new project ID and then run `npx cross-env FIREBASE_TOKEN=$FIREBASE_TOKEN firebase-studio-bootstrap`
// in your terminal.

// IMPORTANT: Make sure to set the correct environment variables in your deployment environment.
// These are required for Firebase to work properly.

export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};
