// This file is automatically generated by Firebase Studio.
// Do not edit manually.

// This file is deprecated and no longer used.
// Firebase configuration is now defined directly in `src/firebase/index.ts`
// to ensure it is only accessed on the client-side.
export const firebaseConfig = {};
